services:
  postgres:
    image: postgres:15
    container_name: credit_db
    environment:
      POSTGRES_DB: creditdb
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgrespass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-networks

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: credit_api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app-networks

volumes:
  postgres_data:

networks:
  app-networks:
    driver: bridge